services:
  web:
    image: "eclipse-temurin:21-jre-alpine"
    entrypoint: "java -jar /app.jar"
    ports:
      - "8080:8080"
    volumes:
      - "./build/libs/spring-boot-0.0.1-SNAPSHOT.jar:/app.jar"
    environment:
      SPRING_PROFILES_ACTIVE: production
    depends_on:
      - db
  db:
    image: "bitnami/postgresql"
    ports:
      - "5432:5432"
    volumes:
      - "./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      POSTGRES_PASSWORD: spring