services:
  web:
    image: "tomcat"
    ports:
      - "8080:8080"
    volumes:
      - "./build/libs/spring-framework-data-access-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war"
    environment:
      SPRING_PROFILES_ACTIVE: production
    depends_on:
      - db
  db:
    image: "bitnami/postgresql"
    ports:
      - "5432:5432"
    volumes:
      - "./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      POSTGRES_PASSWORD: spring